### ISSUE TITLE
Some foldable methods could be usefull

### ISSUE THREAD

**Issue by user471** [emmanueltouzery/prelude.ts#1]
Like min, max, sum

**Comment by emmanueltouzery** [comment]
I'm exactly working on these ;-)
minBy minOn (like the existing sort) same for max and sumBy. On collection so for vector, linkedlist, stream anf hashset. I'll add them through the week-end. I can release right after.

**Comment by user471** [comment]
@emmanueltouzery thanks

**Comment by emmanueltouzery** [comment]
FYI just published 0.4.2 which has the extra methods!
