### ISSUE TITLE
Error calling findAny on an empty HashMap

### ISSUE THREAD

**Issue by bwbuchanan** [emmanueltouzery/prelude.ts#13]
import { HashMap } from 'prelude.ts';
    HashMap<string, string>.empty().findAny(() => true);

Results in:

    TypeError: this.hamt.entries is not a function
        at EmptyHashMap.HashMap.findAny (node_modules/prelude.ts/src/HashMap.ts:381:53)
        at Object.<anonymous> (test.ts:2:33)

**Comment by emmanueltouzery** [comment]
:-(
Sorry.. That is the same as https://github.com/emmanueltouzery/prelude.ts/pull/10 -- i'll fix & republish hopefully late tonight. I need to do better with this class of errors, i'll try to come up with a test or a mechanism to prevent these.

**Comment by emmanueltouzery** [comment]
I release 0.7.11 with the fix. Thank you for the report and sorry for the inconvenience!
