### ISSUE TITLE
Option.getOrThrow() should take Error as argument

### ISSUE THREAD

**Issue by bwbuchanan** [emmanueltouzery/prelude.ts#15]
Option.getOrThrow() currently takes a string as its argument. I think that it should take an Error instance, because throwing bare strings is generally considered poor Javascript coding practice.

Current method:

    getOrThrow(message?: string): T & WithEquality {
        throw message || "getOrThrow called on none!";
    }

Suggested:

    getOrThrow(error?: Error): T & WithEquality {
        throw error || new Error("getOrThrow called on none!");
    }

**Comment by emmanueltouzery** [comment]
Thanks for the suggestion! The reason it's currently implemented the way it is is that I'm concerned with someone porting a legacy codebase to prelude. If that codebase had a practice of throwing things which are not Error, then porting could become harder. On the other hand I suppose one could cast to any to make it work for that legacy's case, like

    getOrThrow(<any>"oops")

not sure what's right in this case. I'll think it through a little more.

**Comment by emmanueltouzery** [comment]
Oh but getOrThrow takes and throws strings! Sorry I checked too fast. You're right this is wrong it should throw errors by default. Maybe it should take Error|string and if given a string, wrap the string in Error for convenience.

**Comment by bwbuchanan** [comment]
Sounds good. I agree.
