### ISSUE TITLE
Option.ofNullable(0) returns None

### ISSUE THREAD

**Issue by bwbuchanan** [emmanueltouzery/prelude.ts#19]
Option.ofNullable uses Javascript "truthiness" as its predicate, instead of comparing against null.

The result of this is that Option.ofNullable(0) returns None, instead of the expected value Some<0>

**Comment by emmanueltouzery** [comment]
sorry about that one... 0.8.1 will be on npm in a few minutes with the fix...

**Comment by emmanueltouzery** [comment]
thanks for the report!
