### ISSUE TITLE
Future Error Type

### ISSUE THREAD

**Issue by dkirchhof** [emmanueltouzery/prelude.ts#21]
Hello,
after replacing another fp library with this one, i was missing the error type of a future.  
Are there any reasons, why you don't allow to use a future like `Future<L, R>`?

**Comment by emmanueltouzery** [comment]
Hello, yes actually this was already discussed in a past issue, I explained it there:
https://github.com/emmanueltouzery/prelude.ts/issues/7#issuecomment-412292369

I think the error type being `any` accurately models what's going on in reality, but I'm interested in any input!

**Comment by dkirchhof** [comment]
Oh sorry, totally missed the linked issue.  
Actually i don't know, if i would even use another type then the default `Error` type - so i will close this issue now. Thanks
